---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-internal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: externaldns-internal-secrets
    creationPolicy: Owner
  data:
    - secretKey: bind_rndc_algorithm
      remoteRef:
        key: bind
        property: externaldns_algorithm
    - secretKey: bind_rndc_secret
      remoteRef:
        key: bind
        property: externaldns_secret
