---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app externaldns-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system

  values:
    fullnameOverride: *app

    domainFilters:
      - toskbot.xyz

    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "10.67.0.2"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "53"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: "toskbot.xyz"
      - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
        value: "true"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: externaldns
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        valueFrom:
          secretKeyRef:
            name: externaldns-internal-secrets
            key: bind_rndc_algorithm
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: externaldns-internal-secrets
            key: bind_rndc_secret

    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-internal-secrets

    policy: sync
    provider: rfc2136

    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M

    serviceMonitor:
      enabled: true

    sources:
      - gateway-httproute
      - service

    txtPrefix: "k8s."

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *app
            patch: |
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
