apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        type: deployment
        annotations:
          secret.reloader.stakater.com/reload: |-
            lidarr-secret,radarr-secret,sonarr-secret
        containers:
          main:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.14.5@sha256:dc72256942ce50d1c8a1aeb5aa85b6ae2680a36eefd2182129d8d210fce78044
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 3000Mi
            env:
              TZ: America/Los_Angeles
              UN_START_DELAY: 30s
              UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local:8989
              UN_SONARR_0_PATHS_0: /complete
              UN_SONARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: SONARR__API_KEY
              UN_RADARR_0_URL: http://radarr.media.svc.cluster.local:7878
              UN_RADARR_0_PATHS_0: /complete
              UN_RADARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: RADARR__API_KEY
              UN_LIDARR_0_URL: http://lidarr.media.svc.cluster.local:8020
              UN_LIDARR_0_PATHS_0: /complete
              UN_LIDARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lidarr-secret
                    key: LIDARR__API_KEY
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
            fsGroup: 3000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100
    service:
      main:
        enabled: false
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: truenas-media
        globalMounts:
          - path: /complete
            subPath: downloads/complete
