---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tandoor-configmap
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: django.db.backends.postgresql
  GUNICORN_MEDIA: "0"
  TIMEZONE: America/New_York
  TANDOOR_PORT: "8080"
  FRACTION_PREF_DEFAULT: "0"
  COMMENT_PREF_DEFAULT: "1"
  SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"
  # SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
  ENABLE_SIGNUP: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tandoor-nginx
data:
  nginx-config: |
    pid /tmp/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      server {
        listen 80;
        server_name _;
        client_max_body_size 128M;
        # serve static files
        location /static/ {
          alias /static/;
        }
        # serve media files
        location /media/ {
          alias /media//;
        }
        # pass requests for dynamic content to gunicorn
        location / {
        proxy_set_header Host $host;
        proxy_pass http://localhost:8080;
        }
      }
      # necessary for unprivileged user
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;
    }
