---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-mediafiles
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-staticfiles
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 5Gi
