---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret tandoor-secret
          configMap.reloader.stakater.com/reload: &configmap tandoor-configmap
        containers:
          main:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: "1.5.24"
            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *configmap
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /accounts/login/
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /accounts/login/
                    port: 8080
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
          nginx:
            image:
              repository: public.ecr.aws/nginx/nginx
              tag: 1.27.3
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
            envFrom:
              - secretRef:
                  name: *secret
    service:
      main:
        ports:
          http:
            port: 80
    persistence:
      mediafiles:
        type: persistentVolumeClaim
        existingClaim: tandoor-mediafiles
        advancedMounts:
          main:
            main:
              - path: /opt/recipes/mediafiles
            nginx:
              - path: /media
      staticfiles:
        type: persistentVolumeClaim
        existingClaim: tandoor-staticfiles
        advancedMounts:
          main:
            main:
              - path: /opt/recipes/staticfiles
            nginx:
              - path: /static
      nginx-config:
        type: configMap
        name: tandoor-nginx
        advancedMounts:
          main:
            nginx:
              - path: /etc/nginx/nginx.conf
                subPath: nginx-config
                readOnly: true
      django-js-reverse:
        type: emptyDir
        mountPath: /opt/recipes/cookbook/static/django_js_reverse
