---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app suwayomi
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      suwayomi:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v1.1.1-r1599
            env:
              TZ: America/New_York
              BIND_PORT: &port 4567
              WEB_UI_CHANNEL: "preview"
              AUTO_DOWNLOAD_CHAPTERS: "true"
              UPDATE_EXCLUDE_UNREAD: "false"
              UPDATE_EXCLUDE_STARTED: "false"
              UPDATE_EXCLUDE_COMPLETED: "false"
              DOWNLOAD_AS_CBZ: "true"
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /home/suwayomi/.local/share/Tachidesk
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: longhorn-ssd
    defaultPodOptions:
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
        fsGroup: 3000
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      main:
        hostnames: ["{{ .Release.Name }}.toskbot.xyz"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: truenas-media
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk/downloads
            subPath: suwayomi
