---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: redpanda-operator
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/redpanda-data/redpanda
  ref:
    tag: v23.1.13
  ignore: |
    # exclude all
    /*
    # include dir for crd
    !/src/go/k8s/config/crd
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redpanda
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.vectorized.io/
