---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  # Pre Flux-Kustomizations
  - ./nfs-pvc.yaml
  # - ./restart-pods-with-stale-nfs.yaml
  # Flux-Kustomizations
  - ./qbittorrent/ks.yaml
  - ./prowlarr/ks.yaml
  # - ./radarr/ks.yaml
  # - ./sonarr/ks.yaml
  # - ./lidarr/ks.yaml
  # - ./navidrome/ks.yaml
  # - ./jellyfin/ks.yaml
  - ./bandcamp-downloader/ks.yaml
  # - ./unpackerr/ks.yaml
  # - ./bazarr/ks.yaml
  - ./komga/ks.yaml
  # - ./miniflux/ks.yaml
  # - ./jellyseerr/ks.yaml
  - ./calibre-web/ks.yaml
  # - ./shiori/ks.yaml
  # - ./ytdl-sub/ks.yaml
  - ./suwayomi/ks.yaml
  - ./komf/ks.yaml

