---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media
provisioner: nfs.csi.k8s.io
parameters:
  archiveOnDelete: "false"
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  storageClassName: media
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.toskbot.xyz
    path: /mnt/user/data/
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: media
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss
