apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-checker-sa
  namespace: media
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-pods-with-stale-nfs-mount
  namespace: media
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      parallelism: 1
      template:
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - kubectl exec kaizoku-0 -- ls /data || kubectl delete pods -l unraid.mover-sensitive=true
            image: ghcr.io/onedr0p/kubernetes-kubectl:1.29.2@sha256:6324f99979877f3ded7647f4efa4df6d73f11bb9d8302dc81ab4a5d38e406867
            imagePullPolicy: IfNotPresent
            name: pod-command-container
          restartPolicy: OnFailure
          serviceAccount: nfs-checker-sa
          serviceAccountName: nfs-checker-sa
          terminationGracePeriodSeconds: 30
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
