---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1s45lrwvwepl4pje5ljp4d4pe7js8rlz0y7c80uxa6llqcdwjhfns76mjuc"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1s45lrwvwepl4pje5ljp4d4pe7js8rlz0y7c80uxa6llqcdwjhfns76mjuc"
stores:
  yaml:
    indent: 2
