---
# yaml-language-server: $schema=https://kubernetes-schemas.toskbot.xyz/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shiori
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/go-shiori/shiori
              tag: v1.8.0
            env:
              SHIORI_DIR: "/config"
            resources:
              requests:
                cpu: 10m
                memory: 1200Mi
              limits:
                memory: 2000Mi
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
            supplementalGroups:
              - 100
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: 8080
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
