---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.7.3
            env:
              TZ: "America/Los_Angeles"
              LOG_LEVEL: "info"
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 5055
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: longhorn-ssd
        size: 10Gi
        globalMounts:
          - path: /app/config
