apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-config
data:
  # file-like keys
  configuration.yaml: |
    default_config:

    http:
      server_host: 0.0.0.0
      ip_ban_enabled: false
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        # Node CIDR
        - 10.66.1.0/24
        - 10.66.2.0/24
        - 10.66.3.0/24
        - 10.42.0.0/16

    automation: !include automations.yaml
    scene: !include scenes.yaml
    template: !include templates.yaml
    sensor: !include sensors.yaml

    recorder:
      db_url: !env_var HASS_POSTGRES_URL
      purge_keep_days: 5
