---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yunikorn
  namespace: dev
spec:
  interval: 10m
  path: ./kubernetes/apps/dev/yunikorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
