apiVersion: batch/v1
kind: Job
metadata:
  name: argo-workflows-initdb
spec:
  template:
    metadata:
      name: argo-workflows-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: initdb
        image: ghcr.io/onedr0p/postgres-init:14.8
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: argo-workflows-postgresql-secret
