---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaizoku
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kaizoku-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Kaizoku
        DATABASE_URL: "postgresql://{{ .KAIZOKU_DATABASE_USER }}:{{ .KAIZOKU_DATABASE_PASSWORD }}@postgres-rw.database.svc.cluster.local/kaizoku"
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .KAIZOKU_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .KAIZOKU_DATABASE_PASSWORD }}"
        INIT_POSTGRES_DBNAME: kaizoku
  dataFrom:
    - extract:
        key: kaizoku
    - extract:
        key: cloudnative-pg
