---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kaizoku
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kaizoku.toskbot.xyz`)
      kind: Rule
      services:
        - name: kaizoku
          port: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaizoku-external-dns
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: kaizoku.toskbot.xyz
