apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - externalsecret.yaml
  - redis.yaml
  - release.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: kaizoku
      app.kubernetes.io/instance: kaizoku
      unraid.mover-sensitive: "true"
