---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kaizoku
spec:
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 5m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-initdb
              tag: 14.8
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: kaizoku-secret
        containers:
          main:
            image:
              repository: ghcr.io/oae/kaizoku
              tag: v1.6.1
            env:
              TZ: America/New_York
              KAIZOKU_PORT: 3000
              REDIS_HOST: redis-kaizoku-master.media.svc.cluster.local
              REDIS_PORT: 6379
            envFrom:
              - secretRef:
                  name: kaizoku-secret
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: 3000
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /data
            subPath: media/manga
