---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: superset
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Superset
        DB_HOST: postgres-rw.database.svc.cluster.local
        DB_USER: superset
        DB_PASS: "{{ .SUPERSET_DATABASE_PASSWORD }}"
        DB_NAME: superset
        DB_PORT: "5432"
        SUPESET_SECRET_KEY: "{{ .SUPERSET_SECRET_KEY }}"
        SQLALCHEMY_DATABASE_URI: "postgresgql://superset:{{ .SUPERSET_DATABASE_PASSWORD }}@postgres-rw.database.csv.cluster.local/superset"
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: superset
        INIT_POSTGRES_PASS: "{{ .SUPERSET_DATABASE_PASSWORD }}"
        INIT_POSTGRES_DBNAME: superset
  dataFrom:
    - extract:
        key: superset
    - extract:
        key: cloudnative-pg

