apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent2
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-scripts,qbittorrent-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent2
        initContainers:
          coredns:
            image:
              repository: mirror.gcr.io/coredns/coredns
              tag: 1.12.3
            args:
              - -conf
              - /etc/coredns/Corefile
            restartPolicy: Always

          gluetun:
            dependsOn:
              - coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              DOT: "off"
              DNS_ADDRESS: "127.0.0.2"
              VPN_SERVICE_PROVIDER: airvpn
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              FIREWALL_VPN_INPUT_PORTS: 13763
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_DEBUG: on
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent2
            restartPolicy: Always
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - (ip rule del table $WIREGUARD_ENDPOINT_PORT; ip -6 rule del table $WIREGUARD_ENDPOINT_PORT) || true
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/qbittorrent2
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 6000Mi
            probes:
              startup:
                enabled: false
              liveness:
                enabled: false
              readiness:
                enabled: false
          # port-forward:
          #   image:
          #     repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
          #     tag: 0.0.4@sha256:838ba41b3c736b23ae30f7e79a2610173f389a5ac6fb2b3e9c7bd482b9353c18
          #   env:
          #     GLUETUN_CONTROL_SERVER_HOST: localhost
          #     GLUETUN_CONTROL_SERVER_PORT: 8000
          #     QBITTORRENT_HOST: localhost
          #     QBITTORRENT_WEBUI_PORT: *port
          #     CRON_ENABLED: true
          #     CRON_SCHEDULE: "*/5 * * * *"
          #     LOG_TIMESTAMP: false
          #   securityContext:
          #     runAsUser: 2000
          #     runAsGroup: 2000
          #     runAsNonRoot: true
          #     allowPrivilegeEscalation: false
          #     readOnlyRootFilesystem: true
          #     capabilities:
          #       drop:
          #         - ALL
        pod:
          securityContext:
            fsGroup: 3000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100
    service:
      main:
        ports:
          http:
            port: *port
    route:
      main:
        hostnames: ["qbit.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn-ssd
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          main:
            main:
              - path: /config
      empty-config:
        type: emptyDir
        advancedMounts:
          main:
            port-forward:
              - path: /config
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: truenas-media
        globalMounts:
          - path: /data/nas
      coredns:
        type: configMap
        name: qbittorrent-coredns
        advancedMounts:
          main:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
                readOnly: true

