---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app komf
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      komf:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: sndxr/komf
              tag: 1.3.0@sha256:166e3dbf2a97c65916ad915abecf8d191515d6c7ffa6c7c0e1ab3f4419f9d559
            env:
              KOMF_KOMGA_BASE_URI: http://komga.media.svc.cluster.local:25600
              KOMF_LOG_LEVEL: INFO
            envFrom:
              - secretRef:
                  name: komf-secret
            resources:
              requests:
                memory: 4282M
                cpu: 15m
              limits:
                memory: 4282M
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: longhorn-ssd
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8085
    persistence:
      configmap:
        enabled: true
        type: configMap
        name: komf-configmap
        globalMounts:
          - path: /config/application.yml
            readOnly: true
            subPath: application.yml
