apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ui
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.toskbot.xyz`)
      kind: Rule
      services:
        - name: jellyfin
          port: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.home.arpa/enabled: "true"
    external-dns.alpha.kubernetes.io/target: ingress.toskbot.xyz
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
    - host: jellyfin.toskbot.xyz
  tls:
  - hosts:
    - jellyfin.toskbot.xyz
