apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0@sha256:37aefd713ba31d51255995261616f1144378887bc5f21665a0ebf851fb85f69a
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 6000Mi
            probes:
              startup:
                enabled: false
              liveness:
                enabled: false
              readiness:
                enabled: false
        pod:
          hostname: qbittorrent
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100
          annotations:
            setGateway: "true"
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn-ssd
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          main:
            main:
              - path: /config
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /data/nas
