---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./cloudnative-pg/ks.yaml
  # - ./redis/ks.yaml
  # - ./elastic-stack/ks.yaml
