---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bandcamp-downloader
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bandcamp-secret
    creationPolicy: Owner
  data:
    - secretKey: cookies.json
      remoteRef:
        key: bandcamp-downloader
        property: cookies.json
