apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bandcamp-downloader
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "0 */3 * * *"
          restartPolicy: OnFailure
        containers:
          main:
            image:
              repository: ghcr.io/otosky/bandcamp-collection-downloader
              tag: 0.0.1@sha256:40ff4d510381a8409e1e689d42533af81fe278674d0416a021babd9311c3a1c8
            command: ["java", "-jar", "/app/bandcamp-collection-downloader.jar"]
            args:
              [
                "-f",
                "flac",
                "-c",
                "/config/cookies.json",
                "-d",
                "/media/bandcamp",
                "olivertosky",
              ]
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: secret
        name: bandcamp-secret
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /media/bandcamp
            subPath: bandcamp/
