apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bandcamp-downloader
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "0 12 * * *"
          restartPolicy: OnFailure
        containers:
          main:
            image:
              repository: otosky/bc-dl
              tag: test
            command: ["java", "-jar", "/app/bandcamp-collection-downloader.jar"]
            args:
              [
                "-f",
                "flac",
                "-c",
                "/config/cookies.json",
                "-d",
                "/media/bandcamp",
                "olivertosky",
              ]
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: secret
        name: bandcamp-secret
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /media/bandcamp
            subPath: bandcamp/
