apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./emqx/ks.yaml
  - ./zigbee/ks.yaml
  - ./home-assistant/ks.yaml
