---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sonarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # SONARR__API_KEY
        key: sonarr
