apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.10.2624@sha256:550d8206663585710556de32e8656b4838e83c9dd79ec271af567b85fa724912
            env:
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
              SONARR__APPLICATION_URL: "https://sonarr.toskbot.xyz"
              SONARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: sonarr-secret
            resources:
              requests:
                cpu: 15m
                memory: 500Mi
              limits:
                memory: 2000Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 100
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
