---
ingress:
  # - hostname: "toskbot.xyz"
  #   service: https://traefik.networking.svc.cluster.local:443
  #   originRequest:
  #     originServerName: ingress.toskbot.xyz
  - hostname: "jellyfin.toskbot.xyz"
    service: http://traefik.networking.svc.cluster.local:80
    originRequest:
      originServerName: ingress.toskbot.xyz
  # - hostname: "*.toskbot.xyz"
  #   service: https://traefik.networking.svc.cluster.local:443
  #   originRequest:
  #     originServerName: ingress.toskbot.xyz
  - service: http_status:404
