apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 22.1.0
      interval: 5m
  values:
    ports:
      websecure:
        tls:
          enabled: true
          certResolver: leresolver
      wireguard:
        port: 51820
        expose: true
        exposedPort: 51820
        protocol: UDP
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        ingressClass: "traefik-external"
        allowCrossNamespace: true
      kubernetesIngress:
        publishedService:
          enabled: true
          pathOverride: networking/traefik
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: traefik-external-service
      spec:
        loadBalancerIP: 192.168.2.232
        externalTrafficPolicy: Local
    additionalArguments:
      - --log.level=DEBUG
      - --serversTransport.insecureSkipVerify=true
      - --entryPoints.wireguard.address=:51820/udp
      - --providers.kubernetesingress.ingressendpoint.hostname=toskbot.xyz
      # - --entryPoints.websecure.forwardedHeaders.trustedIPs=192.168.88.0/24,192.168.2.0/24
      # - --entryPoints.web.forwardedHeaders.trustedIPs=192.168.88.0/24,192.168.2.0/24
