apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 33.1.0
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: default
          domains:
            - main: toskbot.xyz
              sans:
                - "*.toskbot.xyz"
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        ingressClass: "traefik-external"
        allowCrossNamespace: true
      kubernetesIngress:
        publishedService:
          enabled: true
          pathOverride: networking/traefik
    tlsStore:
      default:
        defaultCertificate:
          secretName: toskbot-xyz-tls
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "ingress.toskbot.xyz"
        metallb.universe.tf/allow-shared-ip: traefik-external-service
      spec:
        loadBalancerIP: 10.66.1.100
        externalTrafficPolicy: Local
    additionalArguments:
      - --log.level=DEBUG
      - --serversTransport.insecureSkipVerify=true
      - --providers.kubernetesingress.ingressendpoint.hostname=toskbot.xyz
      # - --entryPoints.websecure.forwardedHeaders.trustedIPs=192.168.88.0/24,192.168.2.0/24
      # - --entryPoints.web.forwardedHeaders.trustedIPs=192.168.88.0/24,192.168.2.0/24
