apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: longhorn-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
        key: longhorn
