apiVersion: batch/v1
kind: Job
metadata:
  name: dagster-initdb
spec:
  template:
    metadata:
      name: dagster-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: initdb
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: dagster-postgres-initdb
