---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        # Authentik
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .SECRET_KEY }}"
        AUTHENTIK_REDIS__DB: "1"
        # Database
        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: &dbUser authentik
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__SSLMODE: "require"
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
