---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark-operator
spec:
  interval: 60m
  chart:
    spec:
      chart: spark-operator
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: flux-system
