---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: externaldns-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/network/externaldns-internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
