---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: ghcr.io/foxcpp/maddy
      tag: 0.6.3
    env:
      DEBUG: "true"
      SMTP_PORT: 465
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.2.234
        externalTrafficPolicy: Local
        ports:
          http:
            port: 2525
          metrics:
            enabled: true
            port: 9749
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: maddy.conf
        mountPath: /data/maddy.conf
        readOnly: true
      data:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        mountPath: /dev/shm
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        memory: 50Mi
