---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Forgejo admin
        username: "{{ .FORGEJO_ADMIN_USERNAME }}"
        password: "{{ .FORGEJO_ADMIN_PASSWORD }}"
        # Forgejo database config
        database-password: "{{ .POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_DBNAME: forgejo
        INIT_POSTGRES_USER: forgejo
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-authentik-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-authentik-oidc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: "{{ .AUTHENTIK_CLIENT_ID }}"
        secret: "{{ .AUTHENTIK_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: forgejo
