---
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-init-db
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: postgres-init
          image: ghcr.io/home-operations/postgres-init:18.4.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: forgejo-secret
