---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prefect-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prefect-postgresql-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Prefect
        connection-string: "postgresql+asyncpg://prefect:{{ .PREFECT_DATABASE_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/prefect"
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: prefect
        INIT_POSTGRES_PASS: "{{ .PREFECT_DATABASE_PASSWORD }}"
        INIT_POSTGRES_DBNAME: prefect
  dataFrom:
    - extract:
        key: prefect
    - extract:
        key: cloudnative-pg

