---
# yaml-language-server: $schema=https://kubernetes-schemas.toskbot.xyz/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: komga
spec:
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/gotson/komga
            tag: 1.7.2
          env:
            TZ: America/New_York
            KOMGA_LIBRARIES_SCAN_CRON: "0 */3 * * * ?"
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
      statefulset:
        volumeClaimTemplates:
          - name: config
            mountPath: /config
            accessMode: ReadWriteOnce
            size: 20Gi
            storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: 25600
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /data
            subPath: media/manga
