---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komga
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 5m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/gotson/komga
              tag: 1.23.5
            env:
              TZ: America/Los_Angeles
              KOMGA_LIBRARIES_SCAN_CRON: "0 */3 * * * ?"
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
            fsGroup: 3000
            fsGroupChangePolicy: "OnRootMismatch"
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              size: 20Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: &port 25600
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: truenas-media
        advancedMounts:
          main:
            main:
              - path: /data
                subPath: manga
              - path: /suwayomi
                subPath: suwayomi
