---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-postgres-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # gitea
        GITEA__DATABASE__PASSWD: "{{ .GITEA_DATABASE_PASSWORD }}"
        GITEA__SECURITY__SECRET_KEY: "{{ .GITEA_SECURITY_SECRET_KEY }}"
        # Postgres Init
        POSTGRES_DB: gitea
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: gitea
        POSTGRES_PASS: "{{ .GITEA_DATABASE_PASSWORD }}"
  dataFrom:
    - extract:
        key: gitea
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .GITEA_ADMIN_USERNAME }}"
        password: "{{ .GITEA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: gitea

