---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PROWLARR__API_KEY
        key: prowlarr
