apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.7.1.3644@sha256:67ed6edafa9bbc55bcae2c4218972caff300154a80e3f4d386dba7d6fca8c2c8
    podAnnotations:
      setGateway: "true"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    env:
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
    envFrom:
      - secretRef:
          name: prowlarr-secret
    hostname: prowlarr
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn-ssd
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
