apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr-nightly
              tag: 1.21.1.4629@sha256:5d8ea2b1ee2867e8e3d4a1066af070464eb437db420ffe61ed94c49ddddb429b
            env:
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__ANALYTICS_ENABLED: "False"
            envFrom:
              - secretRef:
                  name: prowlarr-secret
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
        pod:
          annotations:
            setGateway: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
          hostname: prowlarr
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: *port
