---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_JWT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-machine-auth-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-machine-auth-api-key
    creationPolicy: Owner
  data:
  - secretKey: machine-auth-api-key
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_AUTH_API_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-storage-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-storage-system
    creationPolicy: Owner
  data:
  - secretKey: user-id
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_STORAGE_SYSTEM_USER_ID
  - secretKey: api-key
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_STORAGE_SYSTEM_API_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-storage-system-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-storage-system-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: storage-system-jwt-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_STORAGE_SYSTEM_JWT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-transfer-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-transfer-secret
    creationPolicy: Owner
  data:
  - secretKey: transfer-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_TRANSFER_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-thumbnails-transfer-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-thumbnails-transfer-secret
    creationPolicy: Owner
  data:
  - secretKey: thumbnails-transfer-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_THUMBNAILS_TRANSFER_SECRET
