---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_JWT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-machine-auth-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-machine-auth-api-key
    creationPolicy: Owner
  data:
  - secretKey: machine-auth-api-key
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_AUTH_API_KEY
