---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_JWT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-machine-auth-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-machine-auth-api-key
    creationPolicy: Owner
  data:
  - secretKey: machine-auth-api-key
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_AUTH_API_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-storage-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-storage-system
    creationPolicy: Owner
  data:
  - secretKey: user-id
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_STORAGE_SYSTEM_USER_ID
  - secretKey: api-key
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_STORAGE_SYSTEM_API_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-storage-system-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-storage-system-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: storage-system-jwt-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_STORAGE_SYSTEM_JWT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-transfer-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-transfer-secret
    creationPolicy: Owner
  data:
  - secretKey: transfer-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_TRANSFER_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-thumbnails-transfer-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-thumbnails-transfer-secret
    creationPolicy: Owner
  data:
  - secretKey: thumbnails-transfer-secret
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_THUMBNAILS_TRANSFER_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-ldap-bind-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-ldap-bind-secrets
    creationPolicy: Owner
  data:
  - secretKey: reva-ldap-bind-password
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_REVA_LDAP_BIND
  - secretKey: idp-ldap-bind-password
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_IDP_LDAP_BIND
  - secretKey: graph-ldap-bind-password
    remoteRef:
      key: owncloud-ocis
      property: OWNCLOUD_GRAPH_LDAP_BIND
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-ldap-ca
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-ldap-ca
    creationPolicy: Owner
  data:
  - secretKey: ldap-ca.crt
    remoteRef:
      key: owncloud-ocis-certs
      property: ldap-ca.crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud-ldap-cert
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: owncloud-ldap-cert
    creationPolicy: Owner
  data:
  - secretKey: ldap.key
    remoteRef:
      key: owncloud-ocis-certs
      property: ldap.key
  - secretKey: ldap.crt
    remoteRef:
      key: owncloud-ocis-certs
      property: ldap.crt
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: admin-user
# type: Opaque
# data:
#   # how to generate: base64 encode a UUID V4
#   # example generation command: `cat /proc/sys/kernel/random/uuid | tr -d '\n' | base64`
#   user-id: XXXXXXXXXXXXX
#
#   # how to generate: base64 encode a random string (reasonable long and mixed characters)
#   # example generation command: `tr -cd '[a-zA-Z0-9],.' < /dev/urandom | fold -w 50 | head -n 1 | tr -d '\n' | base64`
#   password: XXXXXXXXXXXXX
#
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: idp-secrets
# type: Opaque
# data:
#   # how to generate: base64 encode a random 32 byte string (mixed characters)
#   # example generation command: `openssl rand 32 | base64`
#   encryption.key: XXXXXXXXXXXXX
#
#   # how to generate: base64 encode a private key (eg. RSA, ensure that you use reasonable long key size)
#   # example generation command: `openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 2> /dev/null | base64 | tr -d '\n'`
#   private-key.pem: XXXXXXXXXXXXX
