---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owncloud-ocis
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/ocis
      sourceRef:
        kind: GitRepository
        name: owncloud-ocis
        namespace: flux-system
  values:
    image:
      repository: owncloud/ocis
      tag: 2.0.0
    insecure:
      oidcIdpInsecure: true
      ocisHttpApiInsecure: true
    store:
      type: redis-sentinel
      nodes:
        - redis.database.svc.cluster.local:26379
    eventhistory:
      store:
        type: redis-sentinel
        nodes:
          - redis.database.svc.cluster.local:26379/redis-master
    secretRefs:
      jwtSecretRef: "owncloud-jwt-secret"
      machineAuthApiKeySecretRef: "owncloud-machine-auth-api-key"
      storagesystemJwtSecretRef: "owncloud-storage-system-jwt-secret"
      storagesystemSecretRef: "owncloud-storage-system"
      thumbnailsSecretRef: "owncloud-thumbnails-transfer-secret"
      transferSecretSecretRef: "owncloud-transfer-secret"
      ldapCaRef: "owncloud-ldap-ca"
      ldapCertRef: "owncloud-ldap-cert"
      ldapSecretRef: "owncloud-ldap-bind-secrets"
      adminUserSecretRef: "owncloud-admin-user"
      idpSecretRef: "owncloud-idp-secrets"
