---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kavita
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.8.4@sha256:9b4693293e0f1f482393cb80abce7e9d11078aabd68f9534bdf46b7fcd0132c5
            resources:
              requests:
                cpu: 50m
                memory: 300Mi
              limits:
                cpu: 500m
                memory: 700Mi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: longhorn-ssd
              globalMounts:
                - path: /kavita/config
    service:
      main:
        ports:
          http:
            port: 5000
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /data
            subPath: media/books
