---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-tenant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-tenant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.env: |
          export MINIO_ROOT_USER="{{ .MINIO_ROOT_USER }}"
          export MINIO_ROOT_PASSWORD="{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: minio-tenant
