---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
spec:
  interval: 15m
  chart:
    spec:
      chart: tenant
      version: 5.0.4
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    tenant:
      name: minio1
      image:
        repository: quay.io/minio/minio
        tag: RELEASE.2023-01-12T02-06-16Z
        pullPolicy: IfNotPresent
      ## Secret name that contains additional environment variable configurations.
      ## The secret is expected to have a key named config.env containing environment variables exports.
      configuration:
        name: minio-tenant-secret
      pools:
        - servers: 4
          name: pool-0
          volumesPerServer: 4
          size: 10Gi
          storageClassName: local-path-ssd
          annotations: {}
          affinity: {}
          labels: {}
          resources: {}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
      mountPath: /export
      subPath: /data
      metrics:
        enabled: false
        port: 9000
        protocol: http
      features:
        bucketDNS: true
        domains: {}
      buckets: []
      users: []
      exposeServices: {}
      prometheusOperator: false
      log:
        disabled: true
      prometheus:
        disabled: true
      logging:
        anonymous: true
        json: true
        quiet: true
      serviceMetadata: {}
      env: []
