---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lakekeeper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lakekeeper-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_DATABASE: lakekeeper_catalog
        INIT_POSTGRES_USER: catalog
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        postgres-password: "{{ .POSTGRES_PASSWORD }}"
        encryption-key: "{{ .ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: lakekeeper
    - extract:
        key: cloudnative-pg

