---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # RADARR__API_KEY
        key: radarr
