---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pod-gateway-vpnconfig
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pod-gateway-vpnconfig
    creationPolicy: Owner
  dataFrom:
    - extract:
        # WIREGUARD_PRIVATE_KEY, WIREGUARD_ADDRESSES, WIREGUARD_PRESHARED_KEY, SERVER_NAMES
        key: airvpn
