---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
resources:
  - ./externalsecret.yaml
  - ./release.yaml
commonLabels:
  app.kubernetes.io/name: pod-gateway
  app.kubernetes.io/instance: pod-gateway
