apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pod-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.13.0@sha256:a5b032e15f7570493977b330a5a86dcffebb807d35685ad803e47afb62d105f2
    podAnnotations:
      secret.reloader.stakater.com/reload: pod-gateway-vpnconfig
    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: 1637
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: 10.0.0.0/8
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: VPN_SERVICE_PROVIDER
            value: airvpn
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: HEALTH_TARGET_ADDRESS
            value: "1.1.1.1"
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 30s
          - name: FIREWALL_VPN_INPUT_PORTS
            value: 13763
          - name: VPN_ENDPOINT_PORT
            value: 1637
        envFrom:
          - secretRef:
              name: pod-gateway-vpnconfig
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      netshoot:
        enabled: true
    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: 13763
            type: udp
          - port: 13763
            type: tcp
    routed_namespaces:
      - media
    settings:
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: 1637
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.12.0@sha256:6f6ab596afd5fef0ca4648eadfb21cd37ba86fa5afa8b85edcc072976a61fbed
