---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opentofu
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opentofu-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OP_CONNECT_HOST: http://onepassword-connect.external-secrets.svc.cluster.local:8080
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
  dataFrom:
    - extract:
        key: opentofu
