---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/bazarr
              tag: 1.5.3@sha256:2f1c32cb1420b2e56f60cfdf7823737eb501fdb2c13669429d23ab3a02e9ad90
            env:
              TZ: America/Los_Angeles
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2000Mi
          subcleaner:
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.5.0
            args:
              - --repo=https://github.com/KBlixt/subcleaner.git
              - --branch=master
              - --depth=1
              - --wait=21600 # 6 hours
              - --root=/add-ons/subcleaner
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
            fsGroup: 3000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: 6767
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: truenas-media
      add-ons:
        enabled: true
        type: emptyDir
