---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
        key: zigbee
