# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: &name airflow
# spec:
#   staticConfigs:
#     - targets:
#         - airflow-statsd.dev.svc.cluster.local:9102
#   metricsPath: /metrics
#   relabelings:
#     - action: replace
#       targetLabel: job
#       replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name unraid
spec:
  staticConfigs:
    - targets:
      - nas.toskbot.xyz:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
