# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
spec:
  interval: 1h
  chart:
    spec:
      chart: temporal
      version: 0.66.0
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    elasticsearch:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    cassandra:
      enabled: false
    server:
      namespaces:
      create: true
      namespace:
        - name: default
          retention: 3d
      additionalInitContainers:
        - name: init-db-default
          image: ghcr.io/home-operations/postgres-init:17.6.0
          imagePullPolicy: IfNotPresent
          env:
            - name: INIT_POSTGRES_DBNAME
              value: temporal
          envFrom:
            - secretRef:
                name: temporal-secret
        - name: init-db-visibility
          image: ghcr.io/home-operations/postgres-init:17.6.0
          imagePullPolicy: IfNotPresent
          env:
            - name: INIT_POSTGRES_DBNAME
              value: temporal_visibility
          envFrom:
            - secretRef:
                name: temporal-secret
      config:
        persistence:
          default:
            driver: "sql"

            sql: &sqlconn
              driver: "postgres12"
              host: postgres-rw.database.svc.cluster.local
              port: 5432
              database: temporal
              user: temporal
              existingSecret: temporal-dbpass
              maxConns: 20
              maxIdleConns: 20
              maxConnLifetime: "1h"

          visibility:
            driver: "sql"

            sql:
              driver: "postgres12"
              host: postgres-rw.database.svc.cluster.local
              port: 5432
              database: temporal_visibility
              user: temporal
              existingSecret: temporal-dbpass
              maxConns: 20
              maxIdleConns: 20
              maxConnLifetime: "1h"
    schema:
      createDatabase:
        enabled: false
      setup:
        enabled: true
      update:
        enabled: true
