---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flink-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://downloads.apache.org/flink/flink-kubernetes-operator-1.12.1/
