---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: media
spec:
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: qbittorrent
  path: ./kubernetes/apps/media/sonarr/app/
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sonarr
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 5m
