---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: suwayomi
  namespace: media
spec:
  path: ./kubernetes/apps/media/suwayomi/app/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: suwayomi
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 5m
