---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.36.1
            env:
              TZ: America/New_York
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "true"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "true"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://z2m.toskbot.xyz
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx.home.svc.cluster.local
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_MQTT_USER:
                valueFrom:
                  secretKeyRef:
                    name: emqx-secret
                    key: AUTH__USER__1__USERNAME
              ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: emqx-secret
                    key: AUTH__USER__1__PASSWORD
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://10.66.3.5:6638
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
          exporter:
            image:
              repository: ghcr.io/kpetremann/mqtt-exporter 
              tag: 1.4.1
            env:
              LOG_LEVEL: "DEBUG"
              LOG_MQTT_MESSAGE: "True"
              MQTT_ADDRESS: "emqx.home.svc.cluster.local"
              MQTT_TOPIC: "zigbee2mqtt/#"
              MQTT_V5_PROTOCOL: "True"
              PROMETHEUS_PORT: "80"
              PROMETHEUS_PREFIX: "zigbee2mqtt_"
              ZIGBEE2MQTT_AVAILABILITY: "True"
              MQTT_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: emqx-secret
                    key: AUTH__USER__1__USERNAME
              MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: emqx-secret
                    key: AUTH__USER__1__PASSWORD
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: 8080
          metrics:
            enabled: true
            port: 80
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
