---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./externalsecret.yaml
  - ./configmap.yaml
  # - ./objectbucketclaim.yaml -- will need something like this deployed via terraform
  - ./release.yaml
labels:
  - pairs:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
