---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  annotations:
    external-dns.alpha.kubernetes.io/public: "true"
spec:
  endpoints:
    - dnsName: ingress.toskbot.xyz
      recordType: CNAME
      targets: ["fe4c7c4f-cea1-4d3a-88d4-3bcd6d1609d8.cfargotunnel.com"]
