---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tofu-controller
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.16.0-rc.5
  url: oci://ghcr.io/flux-iac/charts/tofu-controller
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  dependsOn: []
  interval: 15m
  values:
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: 0.16.0-rc.5
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
