---
# yaml-language-server: $schema=http://kubernetes-schemas.toskbot.xyz/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: home
spec:
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: cloudnative-pg-cluster
      namespace: database
    - name: emqx
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  path: ./kubernetes/apps/home/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: home
  interval: 30m
  retryInterval: 1m
  timeout: 3m
