apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: calibre-web
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`calibre.kube.home.arpa`)
      kind: Rule
      services:
        - name: calibre-web
          port: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web-external-dns
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: calibre.kube.home.arpa
