---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/bjw-s-labs/calibre-web
              tag: 0.6.24@sha256:49169ddd259ac2704f767bca10cb527548b016ebce4ee6c0cc2860ec2a8d5dee
            env:
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539
          enableServiceLinks: false
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: 8083
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /data/media
            subPath: media/books
      cache:
        enabled: true
        type: emptyDir
