---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lidarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # LIDARR__API_KEY
        key: lidarr
