apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/lidarr-develop
      tag: 1.1.3.2982@sha256:4d0e8bd0dd252bf127910c6efc41153364d40a27d907c1a66e0d02d0a4212a8d
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    env:
      LIDARR__INSTANCE_NAME: Lidarr
      LIDARR__PORT: &port 8020
      LIDARR__LOG_LEVEL: info
      LIDARR__APPLICATION_URL: "https://lidarr.kube.home.arpa"
    envFrom:
      - secretRef:
          name: lidarr-secret
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn-ssd
        size: 5Gi
      media:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: /mnt/user/data
        mountPath: /data
    resources:
      requests:
        cpu: 15m
        memory: 500Mi
      limits:
        memory: 2000Mi
