---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: operator
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    env:
      - name: MINIO_OPERATOR_TLS_ENABLE
        value: "on"
      - name: MINIO_CONSOLE_TLS_ENABLE
        value: "on"
      - name: CLUSTER_DOMAIN
        value: "toskbot.xyz"
