---
apiVersion: external-secrets.io/
kind: ExternalSecret
metadata:
  name: navidrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: navidrome
    creationPolicy: Owner
  dataFrom:
    - extract:
        # ND_SPOTIFY_ID, ND_SPOTIFY_SECRET
        key: navidrome
