apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: deluan/navidrome
              tag: sha-4f9418b
            env:
              TZ: America/Los_Angeles
              ND_DATAFOLDER: /config
              ND_ENABLEGRAVATAR: "true"
              ND_LOGLEVEL: info
              ND_MUSICFOLDER: /music
              ND_PORT: &port 80
              ND_PROMETHEUS_ENABLED: "true"
              ND_SCANSCHEDULE: "@every 1h"
            envFrom:
              - secretRef:
                  name: navidrome
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 750Mi
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
            fsGroup: 3000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [10000]
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: longhorn-ssd
    service:
      main:
        ports:
          http:
            port: *port
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
    persistence:
      nas:
        type: persistentVolumeClaim
        existingClaim: truenas-media
        globalMounts:
          - path: /music/lidarr
            readOnly: true
            subPath: music/
          - path: /music/bandcamp
            readOnly: true
            subPath: bandcamp/
