---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: miniflux-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local/miniflux?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: miniflux
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: miniflux
    - extract:
        key: cloudnative-pg
