---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 10m
  path: ./kubernetes/apps/vpn/pod-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
