---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: emqx-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # DASHBOARD__DEFAULT_PASSWORD, AUTH__USER__1__USERNAME, AUTH__USER__1__PASSWORD, AUTH__USER__2__USERNAME, AUTH__USER__2__PASSWORD
        key: emqx
