---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.8.7
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 3
    recreatePods: true
    service:
      type: LoadBalancer
      loadBalancerIP: 10.66.1.108
      externalTrafficPolicy: Local
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
    persistence:
      enabled: true
      storageClassName: openebs-hostpath
      size: 100Mi
  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: DASHBOARD__DEFAULT_PASSWORD
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: AUTH__USER__1__USERNAME
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: AUTH__USER__1__PASSWORD
    - targetPath: emqxConfig.EMQX_AUTH__USER__2__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: AUTH__USER__2__USERNAME
    - targetPath: emqxConfig.EMQX_AUTH__USER__2__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: AUTH__USER__2__PASSWORD
