---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: airflow-postgresql-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Airflow
        connection: "postgresql://airflow:{{ .AIRFLOW_DATABASE_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/airflow"
        # Postgres Init
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: airflow
        INIT_POSTGRES_PASS: "{{ .AIRFLOW_DATABASE_PASSWORD }}"
        INIT_POSTGRES_DBNAME: airflow
  dataFrom:
    - extract:
        key: airflow
    - extract:
        key: cloudnative-pg

