name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        env:
          POETRY_VERSION: "1.4.0"
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.10'
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: poetry install

      - run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
